### ISSUE TITLE
Getting Diagrams from Julia Code

### ISSUE THREAD

**Issue by jpfairbanks** [epatters/Catlab.jl#119]
We have talked about taking an approach similar to Conal Elliott’s compiling to categories, which would require hijacking the Julia interpreter to produce our diagrams/GATExprs. 

Possible tools include Cassette and JuliaInterpreter, which can be used to make call trace graphs. https://gist.github.com/mkborregaard/81825c3d370bb4d8dbfe59c3b2ae4b33

**Comment by epatters** [comment]
You are thinking here of extracting wiring diagrams from arbitrary Julia programs, along the lines discussed in #58?

**Comment by jpfairbanks** [comment]
Yeah I'll post this there. and close this issue.
