### ISSUE TITLE
LinearMaps isomorphic to LinearOperators

### ISSUE THREAD

**Issue by jpfairbanks** [epatters/Catlab.jl#125]
We could use LinearOperators.jl as the instance type for linear maps. This would enable the methods in Krylov.jl instead of IterativeSolvers.jl. Showing compatibility between them would be cool. We have a backend agnostic representations of linear operators (frontend language) with two instances that play the role of backend execution engines. We would get a win in just being able to show GATs as a runtime independent language for modeling linear systems. 

The solvers in Krylov are different being targeted at the Optimization community rather than the NLA community. 

[1] https://github.com/JuliaSmoothOptimizers/LinearOperators.jl 
[2] https://github.com/JuliaSmoothOptimizers/Krylov.jl

**Comment by jpfairbanks** [comment]
A reason to do this is methods like LSMR for solving Least Squares Problems via the normal equations. 

[1] https://juliasmoothoptimizers.github.io/Krylov.jl/dev/solvers/#Krylov.lsmr

**Comment by epatters** [comment]
I really like this idea, both for its practical utility and as a demonstration of multiple instances for a single GAT. I bet it would be easy to implement too, based on how easy it was to make an instance for LinearMaps.jl.

**Comment by jpfairbanks** [comment]
This would be a good first issue, to translate the `@instance` for LinearMaps to an `@instance` for LinearOperators.

**Comment by epatters** [comment]
Resolved by #140. Thanks @bosonbaas!
