### ISSUE TITLE
Method Ambiguity when an instance type defines the theories operations

### ISSUE THREAD

**Issue by jpfairbanks** [epatters/Catlab.jl#141]
@epatters, we previously discussed the case where an instance already defines the term constructor methods from the theory. I think we wanted the `@instance` macro to give a warning if you didn't define it in the instance. The current behavior I am seeing on Catlab v0.6 is that if you don't define the method (for example `compose`) you get an error when you evaluate the `@instance` macro that says the instance does not define the `compose` function. But if you do define it as 

```julia
@instance Epidemiology(OpenPetriDom, OpenPetri) begin
  compose(f::OpenPetri, g::OpenPetri) = OpenPetris.compose(f,g)
  otimes(f::OpenPetri, g::OpenPetri) = OpenPetris.otimes(f,g)
end
```
you get a runtime error of method ambiguity, because Julia doesn't know if you want to call `Main.compose(f,g)` or `OpenPetris.compose(f,g)`.

Is this a user error, or did we not resolve this?

**Comment by epatters** [comment]
IIRC, @mehalter resolved this problem by adding the `@import` keyword for methods that have already been defined elsewhere. So you could write

```julia
@instance Epidemiology(OpenPetriDom, OpenPetri) begin
  @import compose, otimes
end
```

**Comment by jpfairbanks** [comment]
I had forgotten about that and thought that the import statement brought the unicode aliases in from the theory definition. Definitely user error.
