### ISSUE TITLE
Compose \circ in base julia is now vararg

### ISSUE THREAD

**Issue by jpfairbanks** [epatters/Catlab.jl#143]
I was reading the 1.4 release notes and saw this issue: https://github.com/JuliaLang/julia/pull/33568. I'm not sure if this is relevant to catlab, but it might me.

**Comment by jpfairbanks** [comment]
note that \circ() = identity and \circ(f) = f now.

**Comment by epatters** [comment]
Thanks for noticing this change. In previous version of Julia, we had:

```
julia> methods(∘)
# 1 method for generic function "∘":
[1] ∘(f, g) in Base at operators.jl:832
```

In v1.4, we have:

```
julia> methods(∘)
# 2 methods for generic function "∘":
[1] ∘(f, g) in Base at operators.jl:859
[2] ∘(f, g, h...) in Base at operators.jl:860
```

Unfortunately, this will not help us in #131 because the original untyped method for \circ as a binary operator is still present.
