### ISSUE TITLE
Transfer of Instances to Separate Experiment Folder

### ISSUE THREAD

**Issue by bosonbaas** [epatters/Catlab.jl#144]
As we begin to add more `@instances` of `@theories`, we were wondering if it would make sense to have a separate folder in root (possibly called "experiments") to contain these implementations. Inside this folder, we could have a separate directory for each `@instance` with it's own Project.toml and Manifest.toml specification. 

This would keep the Catlab.jl package from obtaining more dependencies as more `@instances` are being developed. @jpfairbanks may also have additional thoughts on this.

**Comment by epatters** [comment]
Oh, interesting. Is the idea to be "mono-repo, multi-package," at least for smaller experiments? That could definitely make sense as way to avoid dependency explosion while still keeping development manageable.

**Comment by bosonbaas** [comment]
Yeah, that would be the idea for smaller experiments! @jpfairbanks made the comment that they will be attempting a similar transition in [SemanticModels.jl](https://github.com/jpfairbanks/SemanticModels.jl) to deal with dependency bloat.

**Comment by jpfairbanks** [comment]
Yeah I think we should manage all the AlgebraicJulia packages that way. A folder for examples/experiments that we aren’t committed to supporting with SemVer and have dependencies that we don’t want Catlab to require. Then if they become useful enough that people want to use them, they get integrated into `src` or a new repo in the AlgebraicJulia org for that example.

**Comment by epatters** [comment]
I am on board with this plan. As a start, the stuff currently in [Catlab.Experimental](https://github.com/epatters/Catlab.jl/tree/master/src/experimental) could be moved out.

**Comment by jpfairbanks** [comment]
Yeah I think each of those files 

-  AlgebraicNets.jl 
-  Experimental.jl 
-  Markov.jl 
-  MathFormulas.jl 

Could be their own subproject. The first step is to make them a project in the `Catlab/examples/` folder with their own Project.toml file and package structure, then when an example matures so that people would want to install it separately, that code becomes a baby repo in the AlgebraicJulia organization. That way we strike a balance between tiny half baked repos and dependency management in Catlab.

**Comment by epatters** [comment]
Agreed. Note that AlgebraicNets.jl + MathFormulas.jl should go together, since they depend on each other, and Experimental.jl is just the parent module. So we only need two sub-projects for these.

**Comment by bosonbaas** [comment]
Thanks for the input! I'll try to get this together and submitted in a PR soon.

**Comment by bosonbaas** [comment]
Question for how testing will work with this new structure:
Do we want the tests of the Experimental packages hooked into the Catlab package testing suite, or should they be independent (like in #147)?

**Comment by jpfairbanks** [comment]
I think they should be separated because these modules are basically examples of how to use Catlab to build some cool technology. So they should be set up as complete Projects with their own tests.

**Comment by epatters** [comment]
I agree that they should be separated. But I also think we should run the sub-projects tests as part of the GitHub CI. This is will prevent the code from becoming bit-rotted over time.
