### ISSUE TITLE
Rename "Doctrines" module to "Theories"

### ISSUE THREAD

**Issue by epatters** [epatters/Catlab.jl#146]
I propose that the module `Catlab.Doctrines` be renamed to `Catlab.Theories`, for several reasons:

1. "Theories" more accurately reflects what is in there, namely a collection of GATs (and default syntax systems for them). Many of these theories are phrased categorically but not all of them, e.g., we will have preorders and posets when #132 is merged.

2. "Doctrine" has a [technical sense](https://ncatlab.org/nlab/show/doctrine) in 2-category theory that we are not taking seriously.

3. "Doctrine," as a plain English word, has unpleasant dogmatic connotations. I do not wish to give the impression that we see category theory as a religion.

Granted, this would be a breaking change motivated entirely by bikeshedding, but I still think it is worth it.

**Comment by jpfairbanks** [comment]
Yes I agree we should do this. @mehalter what do you think about the timing wrt our changes on SM.jl?
