### ISSUE TITLE
Drawing SVGs with Compose changing background color

### ISSUE THREAD

**Issue by jpfairbanks** [epatters/Catlab.jl#159]
Is there a way to set the background color for Compose.jl images? In Atom they have transparent background which means the drawing blend into the background if you use a dark theme. We could also change the line color to grey, which would work on both light and dark backgrounds.

**Comment by epatters** [comment]
I think SVG has support for a background color (at least, you can set the background color in Inkscape), but I don't see any option for background color/fill in the Compose [SVG backend](https://github.com/GiovineItalia/Compose.jl/blob/2cba77d13aab02ca0516abaeac0de6a76ead7830/src/svg.jl#L315).

I can add a background color switch to the Compose backend that just draws a filled rectangle at the bottom of the context.
