### ISSUE TITLE
Special Morphisms in the Programs module

### ISSUE THREAD

**Issue by jpfairbanks** [epatters/Catlab.jl#63]
How do we specify the special morphisms within the `@parse_wiring_diagram` macro?

In the following example, `d` parses correctly, but `e` fails to parse with  a KeyError.
```julia
using Catlab
using Catlab.Programs

P = @present C(FreeBiproductCategory) begin
    X::Ob
    f::Hom(X,X)
end

d = @parse_wiring_diagram P (a::X, b::X) begin
    return f(a), f(b)
end

e = @parse_wiring_diagram P (a::X, b::X) begin
    return mmerge(f(a), f(b))
end
```

```
KeyError: key :mmerge not found

Stacktrace:
 [1] getindex at ./dict.jl:477 [inlined]
 [2] generator at /Users/jfairbanks6/.julia/dev/Catlab/src/core/Present.jl:53 [inlined]
 [3] (::getfield(Catlab.Programs.JuliaPrograms, Symbol("##21#28")){Symbol,Presentation{Symbol},WiringDiagram})(::Port, ::Vararg{Port,N} where N) at /Users/jfairbanks6/.julia/dev/Catlab/src/programs/JuliaPrograms.jl:241
 [4] (::getfield(Catlab.Programs.JuliaPrograms, Symbol("##134#135")))(::getfield(Catlab.Programs.JuliaPrograms, Symbol("##20#27")){Presentation{Symbol},WiringDiagram}, ::Port, ::Port) at ./In[114]:2
 [5] #invokelatest#1(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(Base.invokelatest), ::Any, ::Any, ::Vararg{Any,N} where N) at ./essentials.jl:790
 [6] invokelatest(::Any, ::Any, ::Vararg{Any,N} where N) at ./essentials.jl:789
 [7] parse_wiring_diagram(::Presentation{Symbol}, ::Expr, ::Expr) at /Users/jfairbanks6/.julia/dev/Catlab/src/programs/JuliaPrograms.jl:242
 [8] top-level scope at In[114]:1
```

In general, how are we supposed to refer to the special morphisms such as: `mcopy, mmerge, delete, create, pair, copair, proj1,proj2, incl1, incl2, hom, ev, curry, dual, dunit, dcounit, dagger`?

**Comment by epatters** [comment]
You should never have to use `mcopy` or `delete`, as these are implicit in the syntax.

As for the others, yes, it should be possible to call them like ordinary Julia functions.

**Comment by epatters** [comment]
On second thought, this is some subtlety here. Strictly speaking, there is not a single morphism `mmerge`, but a family of morphisms `mmerge(X)` indexed by objects `X`, so in a naive implementation we would have to write `mmerge(X)(x,y)` instead of just `mmerge(x,y)`. We could supply syntactic sugar to avoid this, but I'm not yet sure how to do that in a generic way.

**Comment by jpfairbanks** [comment]
Can't we infer the type of the `mmerge` from the types of the arguments? Also `mmerge{X}(x,y)` is an available syntax that gets parsed as follows:
```julia
Expr
          head: Symbol call
          args: Array{Any}((3,))
            1: Expr
              head: Symbol curly
              args: Array{Any}((2,))
                1: Symbol mmerge
                2: Symbol X
            2: Symbol x
            3: Symbol y
```

**Comment by epatters** [comment]
We could probably do the type inference, but I'd like to avoid going down that rabbit hole right now. I like the idea of using `mmerge{X}(x,y)`: it is explicit but still fairly readable.

Also, I have some ideas about a more implicit syntax for `mmerge` and `create`, to supplement the implicit syntax for `mcopy` and `mdelete`. I'll work on this soon.

**Comment by jpfairbanks** [comment]
Yeah I get how type inference becomes a rabbit hole. I was just thinking about the first step, where we know the types based on the arguments, which have explicit types. As the programs get bigger that gets harder.

I think implicit syntax is good for extraspecial morphisms like monoid and comonoid objects, with the `foo{T}(s,t)` as a generic syntax for `foo(T)` applied to `(s\otimes t)`

**Comment by epatters** [comment]
The special syntax for `mmerge` and `create` is implemented. For examples, see the unit tests and the [docs](https://epatters.github.io/Catlab.jl/latest/apis/programs/#Catlab.Programs.JuliaPrograms.@parse_wiring_diagram-Tuple{Any,Any}).

The explicit syntax `foo{T}` is up next.

**Comment by epatters** [comment]
OK, it should work now! Let me know if you encounter any bugs.
