### ISSUE TITLE
Wiring diagrams for abelian bicategories of relations

### ISSUE THREAD

**Issue by jpfairbanks** [epatters/Catlab.jl#70]
I think the WiringDiagram code is missing a definition for mplus.

Here is an MWE for the missing definition.

```julia
using Catlab
using Catlab.Doctrines
using Catlab.Syntax
using Catlab.Graphics
using Catlab.Graphics.TikZ
using Catlab.WiringDiagrams
import Catlab.Doctrines: Ob, Hom
wd(x) = to_wiring_diagram(x)
display(x) = to_graphviz(add_junctions!(wd(x)))
R = Ob(FreeAbelianBicategoryRelations, :ℝ)
f = Hom(:f, R,R)
display(otimes(f,f))
ex = mcopy(R)⋅otimes(f,f)⋅mplus(R)
display(ex)
```

```julia
MethodError: no method matching mplus(::Ports{Symbol})
Closest candidates are:
  mplus(!Matched::Catlab.Doctrines.AbelianBicategoryRelations.Ob) at none:0
  mplus(!Matched::Catlab.Doctrines.FreeAbelianBicategoryRelations.Ob) at none:0
```

I guess the first thing to do is introduce a function like for `mmerge` (from src/wiring_diagrams/Layers.jl)

```julia
function mmerge(A::NLayer, n::Int)
  f = WiringLayer(otimes([A for j in 1:n]), A)
  add_wires!(f, i+A.n*(j-1) => i for i in 1:A.n, j in 1:n)
  f
end
```

Somehow it needs to capture the fact that "adding" is happening inside instead of "merging". Then we need to add the corresponding functionality in Graphics for drawing white circles as junctions instead of the black junctions that indicate `mmerge`.

For context, I was trying to use `FreeAbelianBicatRel` as my syntax category for GLA. Where 

1. mcopy/mmerge are the comonoid/monoid pair for copy/filter
2. mplus/coplus are the monoid/comonoid pair for add/split

We need the two sets of monoid/comonoid because of the discussion of range/kernel.

If you just want to talk about matrices, then you only need a [Bimonoid](https://graphicallinearalgebra.net/b/) or [Hopf Monoid](https://graphicallinearalgebra.net/the-theory-of-hopf-monoids/). And thus only need one comonoid and one monoid, and they aren't dual to each other. But for the discussion of solving linear systems, which requires the full adding/adding^{op} and copying/copying^{op} as shown in [this big diagram](https://graphicallinearalgebra.net/2017/10/23/episode-r1-redundancy-and-zebra-snakes/)

I guess there is nothing about the MonoidalCategoryWithBidiagonals that requires mcopy/mmerge to be duals of each other, so I could use that as the base for GLA (edit: if we ignore solving systems for now). Although, GLA has projection/inclusion, so `BiproductCategory` would make sense too.

**Comment by epatters** [comment]
This is definitely related to the part of #49 about wiring diagrams for abelian bicategories of relations. These issues, as well as my recent work on the new Compose.jl diagrams and revamped TikZ diagrams, has got me thinking about the need for better typing and multiple dispatch for wiring diagrams. I will open another issue, probably tomorrow, to discuss this general problem.

**Comment by epatters** [comment]
Relevant discussion in #74.

**Comment by epatters** [comment]
The groundwork for this has been laid in #76 and #77. To complete this thread, we need to:

1. Add wiring diagram support in `Catlab.WiringDiagrams.AlgebraicWiringDiagrams`. We can use the `value` field in `Junction` to distinguish between two the (co)monoid structures, with `(:times,:A)` vs `(:plus,:A)` or something similar.

2. Add Compose.jl and TikZ support in `Catlab.Graphics.WiringDiagramLayouts`.

Both should be straightforward. We should also add Graphviz support, but for that I will need to introduce some style customization mechanism analagous to what now exists for backed-agonistic layout system.

**Comment by epatters** [comment]
Actually, I think it would be better, and more consistent with other parts of the codebase, to type-parametrize Junctions by operation, so that we would write `Junction{:times}` and `Junction{:plus}` or something similar.

**Comment by epatters** [comment]
Part 1 above is done.

**Comment by epatters** [comment]
Everything is finished except Graphviz support, but that is really a separate, more general issue (see comment above).
